version: "3"
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./src/Dockerfile
    depends_on:
      - cache
      - database
    environment:
      - API_PORT=${API_PORT}
      - REDIS_RATE_LIMIT=${REDIS_RATE_LIMIT}
      - REDIS_RATE_TIME=${REDIS_RATE_TIME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "8080:8080"

  cache:
    container_name: cache
    image: redis:6.2-alpine
    volumes:
      - ./config/cache/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - '6379:6379'

  database:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - ./config/data:/docker-entrypoint-initdb.d
